services:
  # FastAPI Application
  exchange_fapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for development (hot reload)
      - ./app/exchange:/AdsAuction/app/exchange
    env_file:
      - ./.env
    environment:
      - EXCHANGE_DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "python", "-c",
      "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz')"]
      interval: 86400s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      #db:
       # condition: service_healthy
      dsp_fapi:
        condition: service_healthy
    networks:
      - AdAuctionNetwork
    restart: on-failure

  dsp_fapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      # Mount source code for development (hot reload)
      - ./app/DSP:/AdsAuction/app/DSP
    env_file:
      - ./.env
    command: fastapi dev app/DSP/main.py --host 0.0.0.0 --port 8001
    healthcheck:
      test: ["CMD", "python", "-c",
      "import urllib.request; urllib.request.urlopen('http://localhost:8001/healthz')"]
      interval: 86400s
      timeout: 5s
      retries: 3
      start_period: 5s
    #depends_on:
      #db:
      #  condition: service_healthy
    networks:
      - AdAuctionNetwork
    restart: on-failure

  prometheus:
    image: prom/prometheus:main
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - AdAuctionNetwork
    depends_on:
      exchange_fapi:
        condition: service_healthy

  grafana:
    image: grafana/grafana:main-distroless-slim
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    networks:
      - AdAuctionNetwork
    depends_on:
      prometheus:
        condition: service_started

  redis:
    image: redis:8.6
    volumes:
      - redis_data:/AdsAuction/app/exchange/redis
    ports: 
      - "6379:6379"
    networks:
      - AdAuctionNetwork
    restart: on-failure

#   PostgreSQL Database
#  db:
#    image: postgres:16-alpine  # Alpine for smaller size, glibc not needed
#    ports:
#      - "5432:5432"  # Expose to host (optional, remove for production)
#    volumes:
#      - AdAuctionPostgres:/var/lib/postgresql/data
#    env_file:
#      - ./.env
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - AdAuctionNetwork
#    restart: on-failure

#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - "5050:80"  # Maps container's port 80 to localhost:5050
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@example.com"  # Login email
#      PGADMIN_DEFAULT_PASSWORD: "admin"          # Login password
#      PGADMIN_CONFIG_SERVER_MODE: 'False'        # Disable server mode for local use
#      GUNICORN_ACCESS_LOGFILE: "/dev/null"
#    networks:
#      - AdAuctionNetwork

networks:
  AdAuctionNetwork:
    driver: bridge

volumes:
  grafanadata:
#  AdAuctionPostgres:
  redis_data:
