global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ows'
    static_configs:
    # TODO this is for development when metrics are out of container.
    # Hence, in main compose target will be 'http:/ows:{ows_metrics_port}/'
    # ip address is found with 'ip addr show docker0 | grep inet'
      - targets: ['172.17.0.1:8043'] 
